# Generated by Django 5.1.6 on 2025-02-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='http://127.0.0.1:8000', max_length=255)),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
